---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule
  - pip install docker
  - pip install flake8
  - pip install ansible-lint
before_script:
  - cd ../
  - mv ansible-nifi nifi
  - cd nifi
script:
  - molecule test --all --parallel
