---
- name: copy nifi configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    mode: "0644"
  with_items:
    - { src: "config/nifi.properties.j2", dest: "{{ nifi_conf_dir }}/nifi.properties" }
    - { src: 'extra-args.properties.j2', dest: "{{ nifi_conf_dir }}/extra-args.properties" }
  notify:
    - restart nifi
  tags: [ deploy, prop, props ]

- name: generate server certificate
  command: keytool -genkeypair -noprompt -alias {{ nifi_server_alias }} -keyalg rsa -keypass {{ nifi_key_pass }} -storepass {{ nifi_keystore_pass }} -keystore {{ nifi_keystore_path }} -dname "{{ nifi_keytool_dname }}"  # noqa 204
  when: nifi_needs_keys
  ignore_errors: yes  # this will fail if the key exists, ignore that failure
  tags: [ config, security ]

- name: export server certificate
  command: keytool -export -alias {{ nifi_server_alias }} -storepass {{ nifi_keystore_pass }} -file {{ nifi_conf_dir }}/server.cer -keystore {{ nifi_keystore_path }}  # noqa 204
  when: nifi_needs_keys
  tags: [ config, security ]

- name: create trust store
  command: keytool -import -noprompt -trustcacerts -alias {{ nifi_server_alias }} -file {{ nifi_conf_dir }}/server.cer -keystore {{ nifi_truststore_path }} -keypass {{ nifi_key_pass }} -storepass {{ nifi_truststore_pass }}  # noqa 204
  when: nifi_needs_keys
  ignore_errors: yes  # this will fail if already imported, ignore that failure
  tags: [ config, security ]

- name: copy user certificate
  copy:
    src: "{{ nifi_ca_cert_local_path }}"
    dest: "{{ nifi_ca_cert_remote_path }}"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
  when: nifi_is_secure

- name: import CA certificate
  command: keytool -importcert -noprompt -file {{ nifi_ca_cert_remote_path }} -alias RSA -keystore {{ nifi_conf_dir }}/cacerts.jks -storepass {{ nifi_truststore_pass }}  # noqa 204
  when: nifi_is_secure
  ignore_errors: yes  # this will fail if already imported, ignore that failure
  tags: [ config, security ]

- name: Ensure cert directories are present
  file:
    state: directory
    owner: "{{ nifi_user }}"
    group: www-data
    path: "{{ nifi_emqtt_cert_dir }}"
  when: nifi_create_mqtt_certs

- name: "Create emqtt SSL certificates"
  include_role:
    name: ssl-certificate
  vars:
    certificate_authority_key: "{{ nifi_emqtt_certificate_authority_key }}"
    certificate_authority_cert: "{{  nifi_emqtt_certificate_authority_cert }}"
    certificates_directory: "{{ nifi_emqtt_certificates_directory }}"
    certificate_authority_key_filename: "{{ nifi_emqtt_certificate_authority_key_filename }}"
    certificate_authority_cert_filename: "{{ nifi_emqtt_certificate_authority_cert_filename }}"
    client_key_filename: "{{ nifi_emqtt_client_key_filename }}"
    client_csr_filename: "{{ nifi_emqtt_client_csr_filename }}"
    client_cert_filename: "{{ nifi_emqtt_client_cert_filename }}"
    certificate_expiry_days: "{{ nifi_emqtt_certificate_expiry_days }}"
    certificate_attributes: "{{ nifi_emqtt_certificate_attributes }}"
    certificates_system_owner: "{{ nifi_user }}"
    certificates_system_group: "{{ nifi_group }}"
  when: nifi_create_mqtt_certs

- name: "Set ownership for the files"
  file:
    path: "{{ item }}"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
  with_items:
    - "{{ nifi_emqtt_certificates_directory }}/{{ nifi_emqtt_client_csr_filename }}"
    - "{{ nifi_emqtt_certificates_directory }}/{{ nifi_emqtt_client_key_filename }}"
    - "{{ nifi_emqtt_certificates_directory }}/{{ nifi_emqtt_client_cert_filename }}"
    - "{{ nifi_emqtt_certificates_directory }}/{{ nifi_emqtt_certificate_authority_cert_filename }}"
  become: true
  become_user: root
  when: nifi_create_mqtt_certs

- name: Create PKCS12 keystore from private key and public certificate
  command: openssl pkcs12 -export -name client-cert -in {{ nifi_emqtt_certificates_directory }}/{{ nifi_emqtt_client_cert_filename }} -inkey {{ nifi_emqtt_certificates_directory }}/{{ nifi_emqtt_client_key_filename }} -out {{ nifi_emqtt_certificates_directory }}/{{ nifi_pkcs_keystore_filename }} -password pass:"{{ nifi_emqtt_secure_password }}" # noqa 204
  become: true
  become_user: "{{ nifi_user }}"
  changed_when: false
  when: nifi_create_mqtt_certs

- name: Convert a PKCS12 keystore into a JKS keystore
  command: keytool -importkeystore -destkeystore {{ nifi_emqtt_certificates_directory }}/{{ nifi_jks_keystore_filename }} -deststorepass {{ nifi_emqtt_secure_password }} -srckeystore {{ nifi_emqtt_certificates_directory }}/{{ nifi_pkcs_keystore_filename }} -srcstorepass {{ nifi_emqtt_secure_password }} -srcstoretype pkcs12 -alias client-cert # noqa 204
  become: true
  become_user: "{{ nifi_user }}"
  changed_when: false
  when: nifi_create_mqtt_certs

- name: Import a server's certificate to the NiFi's trust store.
  command: keytool -import -alias server-cert -file {{ nifi_emqtt_certificates_directory }}/{{ nifi_emqtt_certificate_authority_cert_filename }} -keystore {{ nifi_emqtt_certificates_directory }}/{{ nifi_truststore_filename }} --storepass "{{ nifi_emqtt_secure_password }}" -noprompt # noqa 204
  become: true
  become_user: "{{ nifi_user }}"
  changed_when: false
  when: nifi_create_mqtt_certs

- name: Import a NiFi's certificate to the NiFi's trust store.
  command: keytool -import -alias client-cert -file {{ nifi_emqtt_certificates_directory }}/{{ nifi_emqtt_client_cert_filename }} -keystore {{ nifi_emqtt_certificates_directory }}/{{ nifi_truststore_filename }} --storepass "{{ nifi_emqtt_secure_password }}" -noprompt # noqa 204
  become: true
  become_user: "{{ nifi_user }}"
  changed_when: false
  when: nifi_create_mqtt_certs

- name: Create mqtt jks cerificate
  java_keystore:
    name: certificates
    certificate: "{{ nifi_emqtt_certificate_authority_cert }}"
    private_key: "{{ nifi_emqtt_certificate_authority_key }}"
    password: "{{ nifi_emqtt_secure_password }}"
    dest: "{{ nifi_emqtt_cert_dir }}/keystore.jks"
  when: nifi_create_mqtt_certs

- name: Ensure NiFi owns key files
  file:
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    path: "{{ item }}"
  tags: [ config, security ]
  with_items:
    - "{{ nifi_keystore_path }}"
    - "{{ nifi_truststore_path }}"
  when: nifi_needs_keys

- name: copy nifi configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    mode: "0644"
  with_items:
    - { src: "config/authorizers.xml.j2", dest: "{{ nifi_conf_dir }}/authorizers.xml" }
    - { src: "config/bootstrap.conf.j2", dest: "{{ nifi_conf_dir }}/bootstrap.conf" }
    - { src: "config/bootstrap-notification-services.xml.j2", dest: "{{ nifi_conf_dir }}/bootstrap-notification-services.xml" }
    - { src: "config/logback.xml.j2", dest: "{{ nifi_conf_dir }}/logback.xml" }
    - { src: "config/login-identity-providers.xml.j2", dest: "{{ nifi_conf_dir }}/login-identity-providers.xml" }
    - { src: "config/state-management.xml.j2", dest: "{{ nifi_conf_dir }}/state-management.xml" }
    - { src: "config/zookeeper.properties.j2", dest: "{{ nifi_conf_dir }}/zookeeper.properties" }
  notify:
    - restart nifi
  tags: [ config ]

- name: copy nifi scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    mode: 0755
  with_items:
    - { src: "config/nifi.sh.j2", dest: "{{ nifi_home }}/bin/nifi.sh" }
    - { src: "config/nifi-env.sh.j2", dest: "{{ nifi_home }}/bin/nifi-env.sh" }

- name: Load nifi scripts from script repos
  git:
    repo: "{{ item.git_repo }}"
    version: "{{ item.git_branch }}"
    keyfile: "{{ item.git_key | default('') }}"
    dest: "{{ nifi_home }}/{{ item.destination }}"
  with_items: "{{ nifi_git_scripts }}"

- name: Create file system
  filesystem:
    fstype: "{{ nifi_volume_fs_type }}"
    dev: "{{ nifi_volume_device }}"
  when: nifi_mount_volume

- name: Ensure nifi volume fstab record exists
  mount:
    path: "{{ nifi_volume_mount_point }}"
    src: "{{ nifi_volume_device }}"
    fstype: "{{ nifi_volume_fs_type }}"
    state: mounted
    opts: "{{ nifi_volume_mount_opts }}"
  when: nifi_mount_volume

- name: Have NiFi own the volume directory
  file:
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    path: "{{ nifi_volume_mount_point }}"
  when: nifi_mount_volume

- name: Ensure NiFi is running
  service: name=nifi state=started enabled=yes

- name: Ensure NiFi is restarted
  service: name=nifi state=restarted
  when: nifi_force_restart
