---
- name: copy nifi configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    mode: "0644"
  with_items:
    - { src: "config/nifi.properties.j2", dest: "{{ nifi_conf_dir }}/nifi.properties" }
    - { src: 'extra-args.properties.j2', dest: "{{ nifi_conf_dir }}/extra-args.properties" }
  notify:
    - restart nifi
  tags: [ deploy, prop, props ]

- name: generate server certificate
  command: keytool -genkeypair -noprompt -alias {{ nifi_server_alias }} -keyalg rsa -keypass {{ nifi_key_pass }} -storepass {{ nifi_keystore_pass }} -keystore {{ nifi_keystore_path }} -dname "{{ nifi_keytool_dname }}"  # noqa 204
  when: nifi_needs_keys
  ignore_errors: true  # this will fail if the key exists, ignore that failure
  tags: [ config, security ]

- name: export server certificate
  command: keytool -export -alias {{ nifi_server_alias }} -storepass {{ nifi_keystore_pass }} -file {{ nifi_conf_dir }}/server.cer -keystore {{ nifi_keystore_path }}  # noqa 204
  when: nifi_needs_keys
  tags: [ config, security ]

- name: create trust store
  command: keytool -import -noprompt -trustcacerts -alias {{ nifi_server_alias }} -file {{ nifi_conf_dir }}/server.cer -keystore {{ nifi_truststore_path }} -keypass {{ nifi_key_pass }} -storepass {{ nifi_truststore_pass }}  # noqa 204
  when: nifi_needs_keys
  ignore_errors: true  # this will fail if already imported, ignore that failure
  tags: [ config, security ]

- name: copy user certificate
  copy:
    src: "{{ nifi_ca_cert_local_path }}"
    dest: "{{ nifi_ca_cert_remote_path }}"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
  when: nifi_is_secure

- name: import CA certificate
  command: keytool -importcert -noprompt -file {{ nifi_ca_cert_remote_path }} -alias RSA -keystore {{ nifi_conf_dir }}/cacerts.jks -storepass {{ nifi_truststore_pass }}  # noqa 204
  when: nifi_is_secure
  ignore_errors: true  # this will fail if already imported, ignore that failure
  tags: [ config, security ]

- name: Ensure cert directories are present
  file:
    state: directory
    owner: "{{ nifi_user }}"
    group: www-data
    path: "{{ nifi_emqtt_cert_dir }}"
  when: nifi_create_mqtt_certs

- name: Copy emqtt certificate and key
  copy:
    content: "{{ nifi_emqtt_certificate_authority_key }}\n{{ nifi_emqtt_certificate_authority_cert }}"
    dest: "{{ nifi_emqtt_cert_dir }}/key_cert.pem.txt"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
  when: nifi_create_mqtt_certs

- name: "Generate emqtt keystore"
  command: openssl pkcs12 -export -in "{{ nifi_emqtt_cert_dir }}/key_cert.pem.txt" -out "{{ nifi_emqtt_cert_dir }}/keystore.pkcs12" -noiter -nomaciter -password pass:"{{ nifi_emqtt_secure_password }}"  # noqa 204
  changed_when: false
  when: nifi_create_mqtt_certs

- name: Copy emqtt certificate to file
  copy:
    content: "{{ nifi_emqtt_certificate_authority_cert }}"
    dest: "{{ nifi_emqtt_cert_dir }}/cert.pem"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
  when: nifi_create_mqtt_certs

- name: "Generate emqtt truststore"
  command: keytool -import -file "{{ nifi_emqtt_cert_dir }}/cert.pem" -alias ca_trust -keystore "{{ nifi_emqtt_cert_dir }}/truststore.jks" --storepass "{{ nifi_emqtt_secure_password }}" -noprompt  # noqa 204
  changed_when: false
  when: nifi_create_mqtt_certs

- name: Delete key and root certificate used to generate client certificate
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ nifi_emqtt_cert_dir }}/key_cert.pem.txt"
    - "{{ nifi_emqtt_cert_dir }}/cert.pem"

- name: Create mqtt jks cerificate
  java_keystore:
    name: certificates
    certificate: "{{ nifi_emqtt_certificate_authority_cert }}"
    private_key: "{{ nifi_emqtt_certificate_authority_key }}"
    password: "{{ nifi_emqtt_secure_password }}"
    dest: "{{ nifi_emqtt_cert_dir }}/keystore.jks"
  when: nifi_create_mqtt_certs

- name: Ensure NiFi owns key files
  file:
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    path: "{{ item }}"
  tags: [ config, security ]
  with_items:
    - "{{ nifi_keystore_path }}"
    - "{{ nifi_truststore_path }}"
  when: nifi_needs_keys

- name: copy nifi configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    mode: "0644"
  with_items:
    - { src: "config/authorizers.xml.j2", dest: "{{ nifi_conf_dir }}/authorizers.xml" }
    - { src: "config/bootstrap.conf.j2", dest: "{{ nifi_conf_dir }}/bootstrap.conf" }
    - { src: "config/bootstrap-notification-services.xml.j2", dest: "{{ nifi_conf_dir }}/bootstrap-notification-services.xml" }
    - { src: "config/logback.xml.j2", dest: "{{ nifi_conf_dir }}/logback.xml" }
    - { src: "config/login-identity-providers.xml.j2", dest: "{{ nifi_conf_dir }}/login-identity-providers.xml" }
    - { src: "config/state-management.xml.j2", dest: "{{ nifi_conf_dir }}/state-management.xml" }
    - { src: "config/zookeeper.properties.j2", dest: "{{ nifi_conf_dir }}/zookeeper.properties" }
  notify:
    - restart nifi
  tags: [ config ]

- name: copy nifi scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    mode: 0755
  with_items:
    - { src: "config/nifi.sh.j2", dest: "{{ nifi_home }}/bin/nifi.sh" }
    - { src: "config/nifi-env.sh.j2", dest: "{{ nifi_home }}/bin/nifi-env.sh" }

- name: Load nifi scripts from script repos
  git:
    repo: "{{ item.git_repo }}"
    version: "{{ item.git_branch }}"
    keyfile: "{{ item.git_key | default('') }}"
    dest: "{{ nifi_home }}/{{ item.destination }}"
  with_items: "{{ nifi_git_scripts }}"

- name: Create file system
  filesystem:
    fstype: "{{ nifi_volume_fs_type }}"
    dev: "{{ nifi_volume_device }}"
  when: nifi_mount_volume

- name: Ensure nifi volume fstab record exists
  mount:
    path: "{{ nifi_volume_mount_point }}"
    src: "{{ nifi_volume_device }}"
    fstype: "{{ nifi_volume_fs_type }}"
    state: mounted
    opts: "{{ nifi_volume_mount_opts }}"
  when: nifi_mount_volume

- name: Have NiFi own the volume directory
  file:
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    path: "{{ nifi_volume_mount_point }}"
  when: nifi_mount_volume

- name: Ensure NiFi is running
  service: name=nifi state=started enabled=yes
  when: nifi_perform_restart

- name: Ensure NiFi is restarted
  service: name=nifi state=restarted
  when: nifi_force_restart and nifi_perform_restart
