---
- name: Download toolkit binaries
  get_url:
    url: http://archive.apache.org/dist/nifi/{{ nifi_version }}/{{ nifi_toolkit_archive_name }}
    checksum: "{{ nifi_toolkit_checksum[nifi_version] }}"
    dest: "{{ nifi_base_dir }}/{{ nifi_toolkit_archive_name }}"
    force: no

- name: Unarchive NiFi Toolkit distribution
  unarchive:
    src: "{{ nifi_base_dir }}/{{ nifi_toolkit_archive_name }}"
    dest: "{{ nifi_base_dir }}"
    copy: no
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"

- name: Make sure the NiFi Toolkit distribution dir has right permissions
  file:
    path: "{{ nifi_base_dir }}/nifi-toolkit-{{ nifi_version }}"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    recurse: true

- name: Ensure nifi toolkit symlink
  file:
    src: "{{ nifi_base_dir }}/nifi-toolkit-{{ nifi_version }}"
    dest: "{{ nifi_toolkit_home }}"
    state: link
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"

- name: Create Java Home Helper Script
  template:
    src: "with-java-home.sh.j2"
    dest: "{{ nifi_server_bin_dir[ansible_distribution]|default('/usr/bin') }}/with-java-home.sh"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    mode: 755

- name: Create NiFi Parameters Helper Script
  template:
    src: "set-nifi-parameters.py.j2"
    dest: "{{ nifi_toolkit_home }}/bin/set-nifi-parameters.py"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    mode: 755

- name: Set NiFi Parameters using Helper Script
  shell:
    cmd: "with-java-home.sh ./set-nifi-parameters.py --variables-json '{{ nifi_parameters | to_json }}'"
    chdir: "{{ nifi_toolkit_home }}/bin"
  when: (nifi_parameters | length) > 0
  register: parameter_result

- debug:
    msg: "{{ parameter_result.stdout }}"