---
- include: install.yml
  tags: install
- include: config.yml
  tags: config
- include: set_parameter_contexts.yml
  when:
    - nifi_install_toolkit | bool  # toolkit must be installed
    - nifi_set_parameter_contexts | bool
    - nifi_parameter_contexts is defined
    - nifi_parameter_contexts != None
  tags:
    - config
    - parameter_contexts
- include: test.yml
  when: nifi_test_if_publicly_accessible | bool
  tags: test
