---
- name: Install jq
  include: install_jq.yml
- name: Wait for nifi_web_http_port to become open on the host
  wait_for:
    port: "{{ nifi_web_http_port }}"
    timeout: "{{ nifi_web_http_port_timeout }}"
    delay: 10
- name: Get existing Parameter Contexts
  command: "./bin/cli.sh nifi list-param-contexts -u {{ nifi_api_base_url }} -ot json"
  args:
    chdir: "{{ nifi_base_dir }}/nifi-toolkit-{{ nifi_version }}/"
  register: all_parameter_contexts_result
  environment:
    JAVA_HOME: "{{ nifi_java_home }}"
- name: Save all_parameter_contexts to file
  copy:
    content: "{{ all_parameter_contexts_result.stdout }}"
    dest: "{{ nifi_all_parameter_contexts_result_file }}"
- name: Configure Parameter Contexts
  include_tasks: parameter_contexts/main.yml
  with_items: '{{ nifi_parameter_contexts }}'
  loop_control:
    loop_var: parameter_context
