---
- name: Add Data to NiFi A
  hosts: nifi_a
  tasks:

    - name: Wait for NiFi API A
      uri:
          url: http://localhost:8080/nifi-api/process-groups/root/process-groups
          method: GET
          status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 5

    - name: Create a process group
      uri:
        url: http://localhost:8080/nifi-api/process-groups/root/process-groups
        method: POST
        body: { "revision": { "version": 0 }, "component": { "name": "Test Group" } }
        body_format: json
        headers:
          Content-Type: application/json
        status_code: 201
      register: result

    - debug:
        msg: "{{ result }}"

    - name: Remember group id
      set_fact:
        test_group_id: "{{ result.json.id }}"
      delegate_to: "{{ item }}"
      delegate_facts: True
      with_items: ["nifi_b", "nifi_a"]

    - name: Create a file in the flowfile repo
      file:
        path: "/opt/nifi/nifi-current/flowfile_repository/file_{{ test_group_id }}"
        state: touch
        mode: 755

- name: Backup from NiFi A
  hosts: nifi_a
  tasks:
    - shell: nifi-backup.sh unsafe
    - shell: nifi-backup.sh safe

- name: Restore Flows to NiFi B
  hosts: nifi_b
  tasks:
    - shell: nifi-restore.sh unsafe flows

- name: Check Flows on NiFi B
  hosts: nifi_b
  tasks:

    - name: Wait for NiFi API B
      uri:
          url: http://localhost:8080/nifi-api/process-groups/root/process-groups
          method: GET
          status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 5

    - uri:
        url: http://localhost:8080/nifi-api/process-groups/{{ test_group_id }}
        method: GET
        headers:
          Content-Type: application/json

    - name: Check flowfile exists
      stat:
        path: "/opt/nifi/nifi-current/flowfile_repository/file_{{ test_group_id }}"
      register: result

    - name: Fail if flowfile exists
      fail:
        msg: "Flowfile repository file /opt/nifi/nifi-current/flowfile_repository/file_{{ test_group_id }} exists but should not!"
      when: (result.stat.exists | bool)

- name: Restore Full to NiFi B
  hosts: nifi_b
  tasks:
    - shell: nifi-restore.sh safe full

- name: Check Flows and Repositories on NiFi B
  hosts: nifi_b
  tasks:

    - name: Wait for NiFi API B
      uri:
          url: http://localhost:8080/nifi-api/process-groups/root/process-groups
          method: GET
          status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 5

    - uri:
        url: http://localhost:8080/nifi-api/process-groups/{{ test_group_id }}
        method: GET
        headers:
          Content-Type: application/json

    - name: Check flowfile exists
      stat:
        path: "/opt/nifi/nifi-current/flowfile_repository/file_{{ test_group_id }}"
      register: result

    - name: Fail if flowfile doesn't exist
      fail:
        msg: "Flowfile repository file /opt/nifi/nifi-current/flowfile_repository/file_{{ test_group_id }} does not exist!"
      when: not (result.stat.exists | bool)
