---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Install networking tools needed for testing running service
      apt:
        name: net-tools
        update_cache: yes
        state: present

    - name: "Generate key for client certificate"
      command: openssl genrsa -out /tmp/MyRootCA.key 2048
      changed_when: false

    - name: "Issue certificate for client"
      command: openssl req -x509 -new -nodes -key /tmp/MyRootCA.key -sha256 -days 3650 -out /tmp/MyRootCA.pem
      changed_when: false


  roles:
    - role: nifi
      vars:
        create_mqtt_certs: true
        nifi_emqtt_certificate_authority_cert: "{{ lookup('file', '/tmp/MyRootCA.pem') }}"
        nifi_emqtt_certificate_authority_key: "{{ lookup('file', '/tmp/MyRootCA.key') }}"
        nifi_emqtt_secure_password: "password"
        nifi_emqtt_cert_dir: "/etc/ssl/certs/emqtt"
        nifi_emqtt_kestore_file_dest: "{{ nifi_emqtt_cert_dir }}/keystore.jks"
